/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontrol.kontrol_laporan;
/**
 *
 * @author Hendra Rusdiyanto
 */
public class Utama extends javax.swing.JFrame {
    ResultSet rs;
    kontrol_laporan kl;
   
    /**
     * Creates new form index
     */
    public Utama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        kl = new kontrol_laporan();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DP = new img.DekstopPaneBackground();
        info = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        btnadduser = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnlaporan1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuentrydata = new javax.swing.JMenu();
        masakan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Apotik");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DP.setBackground(new java.awt.Color(204, 204, 204));

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(409, 409, 409))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        DP.setLayer(info, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DP.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                        .addContainerGap(1061, Short.MAX_VALUE)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(info)
                .addGap(39, 39, 39))
        );

        getContentPane().add(DP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 705));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        panelmenu.setBackground(new java.awt.Color(255, 0, 0));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadduser.setBackground(new java.awt.Color(255, 255, 153));
        btnadduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-friend.png"))); // NOI18N
        btnadduser.setText("Tambah User");
        btnadduser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadduser.setIconTextGap(10);
        btnadduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadduserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadduserMouseExited(evt);
            }
        });
        btnadduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadduserActionPerformed(evt);
            }
        });
        panelmenu.add(btnadduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 161, 40));

        btnorder.setBackground(new java.awt.Color(255, 255, 153));
        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnorder.setText("ORDER");
        btnorder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnorder.setIconTextGap(10);
        btnorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnorderMouseExited(evt);
            }
        });
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        panelmenu.add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 40));

        btnlaporan.setBackground(new java.awt.Color(255, 255, 153));
        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer (1).png"))); // NOI18N
        btnlaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlaporan.setIconTextGap(10);
        btnlaporan.setLabel("Cetak Laporan");
        btnlaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanMouseExited(evt);
            }
        });
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        panelmenu.add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 40));

        btnlaporan1.setBackground(new java.awt.Color(255, 255, 153));
        btnlaporan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart.png"))); // NOI18N
        btnlaporan1.setText("Transaksi");
        btnlaporan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlaporan1.setIconTextGap(10);
        btnlaporan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporan1MouseExited(evt);
            }
        });
        btnlaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporan1ActionPerformed(evt);
            }
        });
        panelmenu.add(btnlaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 40));

        getContentPane().add(panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, 705));

        menu.setText("Menu");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);

        keluar.setText("Tutup Aplikasi");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        menu.add(keluar);

        jMenuBar1.add(menu);
        jMenuBar1.add(jMenu2);

        menuentrydata.setText("Master");

        masakan.setText("Data Obat");
        masakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masakanActionPerformed(evt);
            }
        });
        menuentrydata.add(masakan);

        jMenuBar1.add(menuentrydata);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masakanActionPerformed
        // TODO add your handling code here:
        obat m = new obat();
        DP.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_masakanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin keluar dari Aplikasi ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_logoutActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        order_obat ob = new order_obat(this, true);
        ob.setVisible(true);
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseEntered
        // TODO add your handling code here:
        btnorder.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_btnorderMouseEntered

    private void btnorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseExited
        // TODO add your handling code here:
        btnorder.setBackground(new java.awt.Color(255, 255,153));
    }//GEN-LAST:event_btnorderMouseExited

    private void btnadduserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadduserMouseEntered
        // TODO add your handling code here:
        btnadduser.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_btnadduserMouseEntered

    private void btnadduserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadduserMouseExited
        // TODO add your handling code here:
        btnadduser.setBackground(new java.awt.Color(255, 255,153));
    }//GEN-LAST:event_btnadduserMouseExited

    private void btnadduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadduserActionPerformed
        // TODO add your handling code here:
        user u = new user();
        DP.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_btnadduserActionPerformed

    private void btnlaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanMouseEntered
        // TODO add your handling code here:
        btnlaporan.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_btnlaporanMouseEntered

    private void btnlaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanMouseExited
        // TODO add your handling code here:
        btnlaporan.setBackground(new java.awt.Color(255, 255,153));
    }//GEN-LAST:event_btnlaporanMouseExited

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        // TODO add your handling code here:
        String lokasi = "src/report/laporan_transaksi.jrxml";
        HashMap map = new HashMap();
        kl.cetaklaporan(lokasi);
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnlaporan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporan1MouseEntered

    private void btnlaporan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporan1MouseExited

    private void btnlaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporan1ActionPerformed
        // TODO add your handling code here:
        transaksi_obat to = new transaksi_obat(this, true);
        to.setVisible(true);
    }//GEN-LAST:event_btnlaporan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DP;
    public javax.swing.JButton btnadduser;
    public javax.swing.JButton btnlaporan;
    public javax.swing.JButton btnlaporan1;
    public javax.swing.JButton btnorder;
    public javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem logout;
    public javax.swing.JMenuItem masakan;
    public javax.swing.JMenu menu;
    public javax.swing.JMenu menuentrydata;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables

}
